apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bej328wx5-nodejs 
  janus-idp.io/tekton: bej328wx5-nodejs
  backstage.io/kubernetes-id: bej328wx5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bej328wx5-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  