apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bej328wx5-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7c5f84285dd5fee6201aeea877adff533a02fa1e@sha256:386495258d51fccb3f265d4db8786d8f1cff1914e0264ffbad9cb7beb3cefe6b
          name: container-image
