apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bej328wx5-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bej328wx5-nodejs 
  name: bej328wx5-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bej328wx5-nodejs 
